"use client";

import { useEffect, useId, useMemo, useRef, useState } from "react";
import type { GarbageRecord, GarbageSnapshot, LanguageCode } from "@/lib/types";
import { isGarbageSnapshot } from "@/lib/lookups";
import { GARBAGE_CATEGORY_LABELS } from "@/lib/data/garbage";
import { isHelperLocale, searchGarbageWithHelpers, type HelperItem, type HelperSnapshot, validateHelperSnapshot } from "@/lib/garbage-search-helpers";
import { getMessages } from "@/i18n/messages";
import { useLanguage } from "./LanguageProvider";

const helperCache = new Map<string, HelperSnapshot>();
const sourceUrl = "https://catalog.data.metro.tokyo.lg.jp/dataset/t131041d0000000129";

export function GarbageLookup({ onBack, onStartOver }: { onBack: () => void; onStartOver: () => void }) {
  const { lang } = useLanguage(); const copy = (getMessages(lang).lookup as { garbage: Record<string, string> }).garbage; const ui = getMessages(lang).guided.ui;
  const inputRef = useRef<HTMLInputElement>(null), statusRef = useRef<HTMLDivElement>(null), requestRef = useRef<AbortController | null>(null), id = useId();
  const [data, setData] = useState<GarbageSnapshot | null>(null), [helpers, setHelpers] = useState<HelperSnapshot>(), [query, setQuery] = useState(""), [submitted, setSubmitted] = useState(""), [chosen, setChosen] = useState<GarbageRecord | null>(null), [bad, setBad] = useState(false), [retryIndex, setRetryIndex] = useState(0);
  useEffect(() => {
    const controller = new AbortController(); requestRef.current?.abort(); requestRef.current = controller;
    const snapshotRequest = fetch("/api/lookups/shinjuku-garbage-sorting", { signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error("Snapshot unavailable"); const snapshot = await response.json(); if (!isGarbageSnapshot(snapshot)) throw new Error("Invalid snapshot"); return snapshot; });
    const helperRequest = isHelperLocale(lang) ? (helperCache.has(lang) ? Promise.resolve(helperCache.get(lang)) : fetch(`/api/garbage-search-helpers/${lang}`, { signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error("Helpers unavailable"); const helper = await response.json() as HelperSnapshot; helperCache.set(lang, helper); return helper; })) : Promise.resolve(undefined);
    Promise.all([snapshotRequest, helperRequest]).then(([snapshot, helper]) => { if (helper) validateHelperSnapshot(helper, snapshot.records, snapshot.metadata.rawSha256); if (!controller.signal.aborted) { setData(snapshot); setHelpers(helper); } }).catch(() => { if (!controller.signal.aborted) setBad(true); });
    return () => controller.abort();
  }, [lang, retryIndex]);
  const activeHelpers = helpers?.locale === lang ? helpers : undefined;
  const matches = useMemo(() => data ? searchGarbageWithHelpers(data.records, submitted, lang, activeHelpers) : [], [data, submitted, lang, activeHelpers]);
  useEffect(() => { if (submitted || chosen) statusRef.current?.focus(); }, [submitted, chosen]);
  if (bad) return <section className="lookup-sheet"><p>{copy.unavailable}</p><a className="link-action mt-3 inline-block" href={sourceUrl} target="_blank" rel="noopener noreferrer">{copy.sourceLink}</a><div className="mt-3 flex flex-wrap gap-3"><button className="button-secondary" onClick={() => { setBad(false); setRetryIndex((index) => index + 1); }}>{copy.retry}</button><button className="button-secondary" onClick={onBack}>{ui.back}</button><button className="button-secondary" onClick={onStartOver}>{ui.startOver}</button></div></section>;
  if (!data || (lang !== "ja" && !activeHelpers)) return <section className="lookup-sheet" aria-busy="true"><p>{copy.loading}</p></section>;
  const submit = (event: React.FormEvent) => { event.preventDefault(); setChosen(null); setSubmitted(query.slice(0, 80)); };
  const again = () => { setChosen(null); setSubmitted(""); inputRef.current?.focus(); inputRef.current?.select(); };
  return <section className="lookup-sheet"><h2 className="text-2xl font-bold text-ink">{copy.title}</h2><p className="mt-2 text-ink-soft">{copy.intro}</p><form onSubmit={submit} className="mt-5 flex flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor={id}>{copy.inputLabel}</label><input ref={inputRef} id={id} maxLength={80} value={query} onChange={(event) => setQuery(event.target.value)} placeholder={copy.placeholder} className="min-w-0 flex-1 rounded-sm border border-line px-3 py-2"/><button className="button-primary">{copy.search}</button></form><p className="mt-2 text-sm text-ink-soft">{copy.trustNote}</p>{chosen ? <div ref={statusRef} tabIndex={-1} aria-live="polite"><Result record={chosen} copy={copy} lang={lang} helper={activeHelpers?.items.find((item) => item.id === chosen.officialId)}/></div> : submitted && <div ref={statusRef} tabIndex={-1} className="mt-5" role="status" aria-live="polite">{matches.length === 0 ? <p>{copy.noMatch.replace("{query}", submitted)}</p> : matches.length === 1 ? <Result record={matches[0].record} copy={copy} lang={lang} helper={matches[0].helper}/> : <><p>{copy.multiple.replace("{count}", String(matches.length))}</p>{matches.length > 20 && <p>{copy.truncated.replace("{shown}", "20").replace("{count}", String(matches.length))}</p>}<div className="mt-3 grid gap-2">{matches.slice(0, 20).map(({ record, helper }) => <Candidate key={record.id} record={record} helper={helper} copy={copy} onChoose={() => setChosen(record)}/>)}</div></>}</div>}<p className="mt-5 text-sm text-ink-soft">{copy.disclaimer}</p><a className="link-action mt-3 inline-block" target="_blank" rel="noopener noreferrer" href={data.metadata.catalogUrl}>{copy.sourceLink}</a><div className="mt-5 flex flex-wrap gap-3"><button className="button-secondary" onClick={onBack}>{ui.back}</button><button className="button-secondary" onClick={again}>{copy.searchAgain}</button><button className="button-secondary" onClick={onStartOver}>{ui.startOver}</button></div></section>;
}
function Candidate({ record, helper, copy, onChoose }: { record: GarbageRecord; helper?: HelperItem; copy: Record<string, string>; onChoose: () => void }) { if (!helper) return <button aria-label={copy.chooseItemLabel.replace("{item}", record.officialItem)} className="button-secondary text-left" onClick={onChoose} lang="ja">{record.officialItem}</button>; return <button aria-label={`${copy.chooseItemLabel.replace("{item}", helper.n)}. ${copy.officialItemLabel}: ${record.officialItem}`} className="button-secondary text-left" onClick={onChoose}><span className="block font-medium">{helper.n}</span>{helper.r === "check_japanese" && <span className="mt-1 block text-sm text-ink-soft">{copy.checkJapaneseLabel}</span>}<span className="mt-1 block text-sm text-ink-soft">{copy.officialItemLabel}: <span lang="ja">{record.officialItem}</span></span></button>; }
function Result({ record, copy, lang, helper }: { record: GarbageRecord; copy: Record<string, string>; lang: LanguageCode; helper?: HelperItem }) { return <article className="mt-4 rounded-sm border border-line p-4"><h3 className="text-lg font-bold">{copy.resultTitle}</h3>{helper && <p className="mt-3 text-lg"><b>{copy.localizedItemLabel}: </b>{helper.n}</p>}{helper?.r === "check_japanese" && <p className="mt-2 text-sm text-ink-soft">{copy.checkJapaneseLabel}</p>}<p className={helper ? "mt-2" : "mt-3"}><b>{copy.officialItemLabel}: </b><span lang="ja">{record.officialItem}</span></p><p className="mt-2"><b>{copy.categoryLabel}: </b>{GARBAGE_CATEGORY_LABELS[record.categoryId]?.[lang]}</p><p className="mt-2"><b>{copy.officialCategoryLabel}: </b><span lang="ja">{record.officialCategory}</span></p>{record.officialNote && <p className="mt-2 whitespace-pre-line"><b>{copy.officialNoteLabel}: </b><span lang="ja">{record.officialNote}</span></p>}</article>; }
